{
 "title": "Consul Service_To_Service Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source_service",
    "query": {
     "query": "label_values(consul_source_service)"
    }
   },
   {
    "name": "destination_service",
    "query": {
     "query": "label_values(consul_destination_service)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "request_id",
    "query": {}
   },
   { "name": "message_search", "label": "Message contains", "query": "token exchange" }
  ]
 },
 "panels": [
  {
   "title": "Outbound Traffic Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream Traffic: $source_service -> $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_total{local_cluster=~\"$source_service\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by ( local_cluster, consul_destination_service)",
       "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
      }
     ]
    },
    {
     "title": "Upstream Request Response Timeliness: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{local_cluster=~\"$source_service\",consul_destination_target!=\"\"}[10m])) by (le, consul_destination_target))",
       "legendFormat": "{{consul_destination_service}}"
      }
     ]
    },
    {
     "title": "Upstream Request Success Rate: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\",local_cluster=~\"$source_service\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster, consul_destination_service) / sum(irate(envoy_cluster_upstream_rq_xx{local_cluster=~\"$source_service\",consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster,consul_destination_service)\n",
       "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inbound Traffic Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Sent: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_total{consul_destination_datacenter=\"dc1\", local_cluster=~\"$source_service\",\nconsul_destination_service=~\"$destination_service\"}[10m])) by (consul_destination_service, local_cluster)\n",
       "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
      }
     ]
    },
    {
     "title": "Request Success Rate: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class!=\"5\", local_cluster=~\"$source_service\", consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster, consul_destination_service) / sum(irate(envoy_cluster_upstream_rq_xx{consul_destination_service=~\"$destination_service\"}[10m])) by (local_cluster , consul_destination_service)"
      }
     ]
    },
    {
     "title": "Response Success by Status Code: $source_service ->  $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum(increase(envoy_http_downstream_rq_xx{local_cluster=~\"$source_service\", envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (local_cluster, envoy_response_code_class)",
       "legendFormat": "{{envoy_response_code_class}} - {{local_cluster}}"
      }
     ]
    },
    {
     "title": "Request Duration: $source_service -> $destination_service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{consul_destination_datacenter=\"dc1\", consul_destination_service=~\"$destination_service\",local_cluster=~\"$source_service\"}[10m])) by (le, cluster, local_cluster, consul_destination_service))",
       "legendFormat": "{{local_cluster}} -> {{consul_destination_service}}"
      }
     ]
    },
    {
     "title": "Response Success: $source_service ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(increase(envoy_http_downstream_rq_total{local_cluster=~\"$source_service\", envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (local_cluster)",
       "legendFormat": "{{local_cluster}}"
      }
     ]
    },
    {
     "title": "Request Response Rate: $source_service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "sum(irate(envoy_http_downstream_rq_total{local_cluster=~\"$source_service\",envoy_http_conn_manager_prefix=\"public_listener\"}[10m])) by (local_cluster)",
       "legendFormat": "{{local_cluster}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Raw Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "  {cluster=\"ai-security-demo\", service_name=~\"$source_service\", container!~\"vault-agent\", request_id!~\"-|''\"}        \n    |= \"request_id\"\n    | json\n    | regexp `(?:\"request_id\":\\s*\"|request_id=)(?P<request_id_rx>[a-f0-9\\-]+)`\n    | regexp `(?:\"message\":\\s*\"|message=\")(?P<message_rx>[^\"]*)\"`                                                                         \n    | label_format request_id=`{{ or .request_id .request_id_rx }}`, message=`{{ or .message .message_rx }}` \n    | request_id !~ \"-|^$\"                            \n    | request_id=~\"$request_id\"\n    | message =~ \"(?i).*${message_search:regex}.*\""
    }
   ]
  }
 ]
}